=== altaccPran/TE-ASSIGNMENTS/a4/employees.dtd
<!ELEMENT employees (employee+)>

<!ELEMENT employee (name, department, designation, salary, experience, email, joiningDate)>

<!ATTLIST employee empId ID REQUIRED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT department (#PCDATA)>
<!ELEMENT designation (#PCDATA)>
<!ELEMENT salary (#PCDATA)>
<!ELEMENT experience (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT joiningDate (#PCDATA)>

=== altaccPran/TE-ASSIGNMENTS/a4/employees.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet type="text/xsl" href="employees.xsl"?>

<!DOCTYPE employees SYSTEM "employees.dtd">

<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="employees.xsd">

    <employee empId="E101">
        <name>Amit Shah</name>
        <department>IT</department>
        <designation>Software Engineer</designation>
        <salary>60000</salary>
        <experience>3</experience>
        <email>amit@email.com</email>
        <joiningDate>2022-06-15</joiningDate>
    </employee>

    <employee empId="E102">
        <name>Riya Sharma</name>
        <department>HR</department>
        <designation>HR Manager</designation>
        <salary>75000</salary>
        <experience>5</experience>
        <email>riya@email.com</email>
        <joiningDate>2020-04-10</joiningDate>
    </employee>

    <employee empId="E103">
        <name>Neha Verma</name>
        <department>IT</department>
        <designation>Web Developer</designation>
        <salary>55000</salary>
        <experience>2</experience>
        <email>neha@email.com</email>
        <joiningDate>2023-01-12</joiningDate>
    </employee>

    <employee empId="E104">
        <name>Rahul Singh</name>
        <department>Marketing</department>
        <designation>Executive</designation>
        <salary>45000</salary>
        <experience>1</experience>
        <email>rahul@email.com</email>
        <joiningDate>2023-03-20</joiningDate>
    </employee>

    <employee empId="E105">
        <name>Pooja Kulkarni</name>
        <department>Finance</department>
        <designation>Analyst</designation>
        <salary>68000</salary>
        <experience>4</experience>
        <email>pooja@email.com</email>
        <joiningDate>2021-09-18</joiningDate>
    </employee>

</employees>
